name: Static checks
# See https://github.com/lampe-games/godot-open-rts/blob/main/.github/workflows/main.yml
# for source and example

on:
  push:
    branches: [ "main", "using_godot_4.2" ]
  pull_request:
    branches: [ "main", "using_godot_4.2" ]

jobs:
  static-checks:
    name: 'Static checks'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: create-requirements-if-not-exists
      run: |
        if [ ! -f requirements.txt ]; then
          echo "gdtoolkit==4.*" > requirements.txt
        fi
      shell: bash

    - id: install-python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        cache: "pip"

    - id: upgrade-setuptools
      run: pip install --upgrade setuptools
      shell: bash

    - id: install-gdtoolkit
      run: pip install git+https://github.com/Scony/godot-gdscript-toolkit.git
      shell: bash
    
    - id: run-gdformat
      run: gdformat --check .
    
    - id: run-gdlint
      run: gdlint .